[package]
name = "reliableq-db"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
reliableq-core.workspace = true
sqlx.workspace = true
tracing.workspace = true
tokio.workspace = true
anyhow.workspace = true

[dev-dependencies]
uuid.workspace = true
