//! `reliableq-bench report`: reads every raw `RunResult` under
//! `benchmarks/results/`, groups by scenario + parameters, and writes
//! `docs/benchmarking/results.md` plus SVG charts under
//! `benchmarks/reports/` — computed directly from the raw JSON, never
//! hand-edited (docs/benchmarking/design.md sec. 9).

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use plotters::prelude::*;

use crate::result::RunResult;

struct Group {
    scenario: String,
    params: String,
    runs: Vec<RunResult>,
}

fn group_runs(runs: Vec<RunResult>) -> Vec<Group> {
    let mut map: BTreeMap<(String, String), Vec<RunResult>> = BTreeMap::new();
    for run in runs {
        let key = (run.scenario.clone(), run.scenario_params.to_string());
        map.entry(key).or_default().push(run);
    }
    map.into_iter()
        .map(|((scenario, params), runs)| Group {
            scenario,
            params,
            runs,
        })
        .collect()
}

fn mean(values: &[f64]) -> f64 {
    if values.is_empty() {
        0.0
    } else {
        values.iter().sum::<f64>() / values.len() as f64
    }
}

fn fmt_opt(v: Option<f64>) -> String {
    match v {
        Some(v) => format!("{v:.1}"),
        None => "n/a".to_string(),
    }
}

pub fn generate(results_dir: &Path, docs_out: &Path, charts_out: &Path) -> anyhow::Result<()> {
    let all_runs = RunResult::load_all(results_dir)?;
    let total_raw = all_runs.len();
    let dirty_count = all_runs.iter().filter(|r| r.git_dirty).count();
    if dirty_count > 0 {
        tracing::warn!(
            count = dirty_count,
            "excluding run(s) recorded from a dirty worktree"
        );
    }
    let clean_runs: Vec<RunResult> = all_runs.into_iter().filter(|r| !r.git_dirty).collect();
    std::fs::create_dir_all(charts_out)?;

    let mut md = String::new();
    writeln!(md, "# ReliableQ Benchmark Results\n")?;
    writeln!(
        md,
        "Generated by `reliableq-bench report` from {} raw run file(s) under \
         `benchmarks/results/` ({} excluded for a dirty worktree). \
         Every number below comes from that raw data — nothing here is \
         hand-typed. See [`docs/benchmarking/design.md`](design.md) for \
         methodology, workload model, and known noise sources.\n",
        total_raw, dirty_count
    )?;
    writeln!(
        md,
        "**These are local-machine benchmarks, not universal capacity claims** — see design.md sec. 8 for the specific environment and its known sources of noise.\n"
    )?;

    if clean_runs.is_empty() {
        writeln!(md, "No clean (non-dirty) benchmark runs found yet.\n")?;
        std::fs::write(docs_out, md)?;
        return Ok(());
    }

    // --- Executive summary: environment, from the first run. ---
    let env_run = &clean_runs[0];
    writeln!(md, "## Environment\n")?;
    writeln!(md, "| Field | Value |")?;
    writeln!(md, "|---|---|")?;
    writeln!(md, "| Git commit | `{}` |", env_run.git_commit)?;
    writeln!(md, "| Rust | {} |", env_run.rust_version)?;
    writeln!(
        md,
        "| OS | {} {} ({}) |",
        env_run.os, env_run.os_version, env_run.architecture
    )?;
    writeln!(
        md,
        "| CPU | {} |",
        env_run
            .cpu_model
            .clone()
            .unwrap_or_else(|| "unavailable".into())
    )?;
    writeln!(md, "| Logical CPUs | {} |", env_run.logical_cpu_count)?;
    writeln!(
        md,
        "| Memory | {} |",
        env_run
            .memory_bytes
            .map(|b| format!("{:.1} GiB", b as f64 / 1024.0 / 1024.0 / 1024.0))
            .unwrap_or_else(|| "unavailable".into())
    )?;
    writeln!(
        md,
        "| Docker | {} |",
        env_run
            .docker_version
            .clone()
            .unwrap_or_else(|| "unavailable".into())
    )?;
    writeln!(
        md,
        "| PostgreSQL | {} |",
        env_run
            .postgres_version
            .clone()
            .unwrap_or_else(|| "unavailable".into())
    )?;
    writeln!(md, "| Build profile | {} |\n", env_run.build_profile)?;

    // --- Correctness summary. ---
    let total_runs = clean_runs.len();
    let failed_runs: Vec<&RunResult> = clean_runs
        .iter()
        .filter(|r| !r.correctness_results.passed)
        .collect();
    writeln!(md, "## Correctness gate\n")?;
    writeln!(
        md,
        "{}/{} runs passed every correctness check (docs/benchmarking/design.md sec. 7). \
         Any run below with a failed gate has its performance numbers reported but \
         **must not** be read as valid — see `correctness_results.failures` in its raw JSON.\n",
        total_runs - failed_runs.len(),
        total_runs
    )?;
    if !failed_runs.is_empty() {
        writeln!(md, "**Failed-gate runs:**\n")?;
        for run in &failed_runs {
            writeln!(
                md,
                "- `{}` params `{}` run {}: {}",
                run.scenario,
                run.scenario_params,
                run.run_number,
                run.correctness_results.failures.join("; ")
            )?;
        }
        writeln!(md)?;
    }

    let groups = group_runs(clean_runs);
    let mut by_scenario: BTreeMap<String, Vec<&Group>> = BTreeMap::new();
    for g in &groups {
        by_scenario.entry(g.scenario.clone()).or_default().push(g);
    }

    writeln!(md, "## Results by scenario\n")?;
    for (scenario, groups) in &by_scenario {
        writeln!(md, "### `{scenario}`\n")?;
        writeln!(
            md,
            "| Params | Runs | Throughput ({}) | p50 (ms) | p95 (ms) | p99 (ms) | Max (ms) | Correctness |",
            groups[0].runs[0].throughput.unit
        )?;
        writeln!(md, "|---|---|---|---|---|---|---|---|")?;
        for group in groups.iter() {
            let throughputs: Vec<f64> = group.runs.iter().map(|r| r.throughput.value).collect();
            let p50s: Vec<f64> = group
                .runs
                .iter()
                .filter_map(|r| r.latency_percentiles.p50)
                .collect();
            let p95s: Vec<f64> = group
                .runs
                .iter()
                .filter_map(|r| r.latency_percentiles.p95)
                .collect();
            let p99s: Vec<f64> = group
                .runs
                .iter()
                .filter_map(|r| r.latency_percentiles.p99)
                .collect();
            let maxs: Vec<f64> = group
                .runs
                .iter()
                .filter_map(|r| r.latency_percentiles.max)
                .collect();
            let all_pass = group.runs.iter().all(|r| r.correctness_results.passed);
            writeln!(
                md,
                "| `{}` | {} | {:.1} | {} | {} | {} | {} | {} |",
                group.params,
                group.runs.len(),
                mean(&throughputs),
                fmt_opt(if p50s.is_empty() {
                    None
                } else {
                    Some(mean(&p50s))
                }),
                fmt_opt(if p95s.is_empty() {
                    None
                } else {
                    Some(mean(&p95s))
                }),
                fmt_opt(if p99s.is_empty() {
                    None
                } else {
                    Some(mean(&p99s))
                }),
                fmt_opt(if maxs.is_empty() {
                    None
                } else {
                    Some(mean(&maxs))
                }),
                if all_pass { "pass" } else { "**FAIL**" }
            )?;
        }
        writeln!(md)?;
    }

    // --- Charts, generated straight from the grouped raw data. ---
    writeln!(md, "## Charts\n")?;
    if let Some(path) = chart_throughput_vs_concurrency(&by_scenario, charts_out)? {
        writeln!(md, "![Throughput vs worker concurrency]({})\n", rel(&path))?;
    }
    if let Some(path) = chart_retry_amplification(&by_scenario, charts_out)? {
        writeln!(
            md,
            "![Retry amplification vs transient failure rate]({})\n",
            rel(&path)
        )?;
    }
    if let Some(path) = chart_backlog_drain(&by_scenario, charts_out)? {
        writeln!(md, "![Backlog queue depth over time]({})\n", rel(&path))?;
    }

    writeln!(md, "## Reproduction\n")?;
    writeln!(
        md,
        "```bash\nmake up && make migrate\ncargo build --workspace --release\nmake bench-quick   # or: make bench-full\nmake bench-report\n```\n"
    )?;
    writeln!(
        md,
        "Raw results live under `benchmarks/results/<scenario>/<params>/`. \
         Regenerate this file and its charts from that raw data alone with \
         `make bench-report` — nothing in this document is hand-edited."
    )?;

    std::fs::write(docs_out, md)?;
    Ok(())
}

fn rel(chart_path: &Path) -> String {
    format!(
        "../../benchmarks/reports/{}",
        chart_path.file_name().unwrap().to_string_lossy()
    )
}

fn chart_throughput_vs_concurrency(
    by_scenario: &BTreeMap<String, Vec<&Group>>,
    out_dir: &Path,
) -> anyhow::Result<Option<std::path::PathBuf>> {
    let Some(groups) = by_scenario.get("execution") else {
        return Ok(None);
    };
    let mut points: Vec<(f64, f64, u64)> = Vec::new();
    for g in groups {
        let parsed: serde_json::Value = g.runs[0].scenario_params.clone();
        let concurrency = parsed["worker_concurrency"].as_f64().unwrap_or(0.0);
        let latency = parsed["downstream_latency_ms"].as_u64().unwrap_or(0);
        let throughput = mean(
            &g.runs
                .iter()
                .map(|r| r.throughput.value)
                .collect::<Vec<_>>(),
        );
        points.push((concurrency, throughput, latency));
    }
    if points.is_empty() {
        return Ok(None);
    }
    points.sort_by(|a, b| a.2.cmp(&b.2).then(a.0.partial_cmp(&b.0).unwrap()));

    let path = out_dir.join("throughput_vs_concurrency.svg");
    let max_x = points.iter().map(|p| p.0).fold(1.0, f64::max);
    let max_y = points.iter().map(|p| p.1).fold(1.0, f64::max) * 1.1;
    {
        let root = SVGBackend::new(&path, (720, 480)).into_drawing_area();
        root.fill(&WHITE)?;
        let mut chart = ChartBuilder::on(&root)
            .caption(
                "Execution throughput vs worker concurrency",
                ("sans-serif", 20),
            )
            .margin(20)
            .x_label_area_size(40)
            .y_label_area_size(50)
            .build_cartesian_2d(0.0..max_x + 1.0, 0.0..max_y)?;
        chart
            .configure_mesh()
            .x_desc("worker concurrency")
            .y_desc("jobs/sec")
            .draw()?;

        for (idx, latency) in [0u64, 100u64].into_iter().enumerate() {
            let series: Vec<(f64, f64)> = points
                .iter()
                .filter(|p| p.2 == latency)
                .map(|p| (p.0, p.1))
                .collect();
            if series.is_empty() {
                continue;
            }
            let color = [&RED, &BLUE][idx % 2];
            chart
                .draw_series(LineSeries::new(series.clone(), color))?
                .label(format!("{latency}ms downstream"))
                .legend(move |(x, y)| PathElement::new(vec![(x, y), (x + 20, y)], *color));
            chart.draw_series(
                series
                    .iter()
                    .map(|(x, y)| Circle::new((*x, *y), 3, color.filled())),
            )?;
        }
        chart
            .configure_series_labels()
            .background_style(WHITE.mix(0.8))
            .draw()?;
        root.present()?;
    }
    Ok(Some(path))
}

fn chart_retry_amplification(
    by_scenario: &BTreeMap<String, Vec<&Group>>,
    out_dir: &Path,
) -> anyhow::Result<Option<std::path::PathBuf>> {
    let Some(groups) = by_scenario.get("retry_degradation") else {
        return Ok(None);
    };
    let mut points: Vec<(f64, f64)> = Vec::new();
    for g in groups {
        let parsed: serde_json::Value = g.runs[0].scenario_params.clone();
        let rate = parsed["transient_failure_rate"].as_f64().unwrap_or(0.0);
        let amp = mean(
            &g.runs
                .iter()
                .filter_map(|r| r.extra.get("retry_amplification").and_then(|v| v.as_f64()))
                .collect::<Vec<_>>(),
        );
        points.push((rate, amp));
    }
    if points.is_empty() {
        return Ok(None);
    }
    points.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap());

    let path = out_dir.join("retry_amplification.svg");
    let max_y = points.iter().map(|p| p.1).fold(1.0, f64::max) * 1.2;
    {
        let root = SVGBackend::new(&path, (720, 480)).into_drawing_area();
        root.fill(&WHITE)?;
        let mut chart = ChartBuilder::on(&root)
            .caption(
                "Retry amplification vs transient failure rate",
                ("sans-serif", 20),
            )
            .margin(20)
            .x_label_area_size(40)
            .y_label_area_size(50)
            .build_cartesian_2d(0.0..1.0, 1.0..max_y.max(1.5))?;
        chart
            .configure_mesh()
            .x_desc("transient failure rate")
            .y_desc("attempts / logical job")
            .draw()?;
        chart.draw_series(LineSeries::new(points.clone(), &RED))?;
        chart.draw_series(
            points
                .iter()
                .map(|(x, y)| Circle::new((*x, *y), 3, RED.filled())),
        )?;
        root.present()?;
    }
    Ok(Some(path))
}

fn chart_backlog_drain(
    by_scenario: &BTreeMap<String, Vec<&Group>>,
    out_dir: &Path,
) -> anyhow::Result<Option<std::path::PathBuf>> {
    let Some(groups) = by_scenario.get("backlog") else {
        return Ok(None);
    };
    let path = out_dir.join("backlog_drain.svg");
    let mut any_series = false;
    let max_x = groups
        .iter()
        .flat_map(|g| g.runs.iter())
        .filter_map(|r| r.extra.get("queue_depth_over_time"))
        .flat_map(|v| v.as_array().cloned().unwrap_or_default())
        .filter_map(|p| p["t_secs"].as_f64())
        .fold(1.0, f64::max);
    let max_y = groups
        .iter()
        .flat_map(|g| g.runs.iter())
        .filter_map(|r| r.extra.get("queue_depth_over_time"))
        .flat_map(|v| v.as_array().cloned().unwrap_or_default())
        .filter_map(|p| p["depth"].as_f64())
        .fold(1.0, f64::max);

    {
        let root = SVGBackend::new(&path, (720, 480)).into_drawing_area();
        root.fill(&WHITE)?;
        let mut chart = ChartBuilder::on(&root)
            .caption(
                "Backlog queue depth over time (first run per backlog size)",
                ("sans-serif", 18),
            )
            .margin(20)
            .x_label_area_size(40)
            .y_label_area_size(60)
            .build_cartesian_2d(0.0..max_x.max(1.0), 0.0..max_y.max(1.0))?;
        chart
            .configure_mesh()
            .x_desc("seconds")
            .y_desc("queue depth")
            .draw()?;

        let colors = [&RED, &BLUE, &GREEN, &MAGENTA];
        for (idx, group) in groups.iter().enumerate() {
            let Some(first_run) = group.runs.first() else {
                continue;
            };
            let Some(series_val) = first_run.extra.get("queue_depth_over_time") else {
                continue;
            };
            let series: Vec<(f64, f64)> = series_val
                .as_array()
                .cloned()
                .unwrap_or_default()
                .iter()
                .filter_map(|p| Some((p["t_secs"].as_f64()?, p["depth"].as_f64()?)))
                .collect();
            if series.is_empty() {
                continue;
            }
            any_series = true;
            let color = colors[idx % colors.len()];
            chart
                .draw_series(LineSeries::new(series, color))?
                .label(group.params.clone())
                .legend(move |(x, y)| PathElement::new(vec![(x, y), (x + 20, y)], *color));
        }
        chart
            .configure_series_labels()
            .background_style(WHITE.mix(0.8))
            .draw()?;
        root.present()?;
    }
    Ok(if any_series { Some(path) } else { None })
}
